server:
  port: 8080
spring:
  application:
    name: yangxj96-serve-flow
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/yangxj96_saas_db?currentSchema=db_flow&nullCatalogMeansCurrent=true
    username: postgres
    password: QuVsKppcWvwwX2Vv
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    password: QuVsKppcWvwwX2Vv
    port: 6379
    database: 10
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    deployment-mode: never-fail
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.165:8848
        ip: 192.168.2.29
#        server-addr: 192.168.31.164:8848
#        ip: 192.168.31.149

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.yangxj96.bean.flow
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: false
      logic-delete-value: true

yangxj96:
  security:
    enable: false
    store-type: redis
  db:
    security-db: 9
    # 当前项目版本低于3.0.0 导致自动配置包不适用
    redis-enable: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    yangxj96: debug
  group:
    yangxj96:
      - io.github.yangxj96.starter.common.autoconfigure
      - io.github.yangxj96.starter.db.autoconfigure
      - io.github.yangxj96.starter.remote.autoconfigure
      - io.github.yangxj96.starter.security.autoconfigure