version: '3'
services:
  yangxj96-rabbitmq:
    image: rabbitmq:3.11.5
    container_name: yangxj96-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: QPOCe^7Q5qtoPD&O
    volumes:
      - "/docker/RabbitMQ/config/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "/docker/RabbitMQ/config/:/etc/rabbitmq/conf.d/"
    restart: always
    privileged: true
    network_mode: "host"
