version: '3'
services:
  yangxj96-pgsql:
    image: postgis/postgis:15-master
    container_name: yangxj96-pgsql
    restart: always
    environment:
      POSTGRES_PASSWORD: QuVsKppcWvwwX2Vv
      #LANG: zh_CN.utf8
    volumes:
      - "/docker/PostgreSQL/data:/var/lib/postgresql/data"
      - "/docker/PostgreSQL/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
    privileged: true
    network_mode: "host"
