version: '3'
services:
  yangxj96-redis:
    image: redis:7.0.5-alpine
    container_name: yangxj96-redis
    restart: always
    privileged: true
    network_mode: "host"
    command: redis-server --port 6379 --requirepass QuVsKppcWvwwX2Vv  --appendonly yes

