version: "3.8"

services:
  yangxj96-pgsql:
    image: postgis/postgis:15-master
    container_name: yangxj96-pgsql
    restart: always
    privileged: true
    network_mode: host
    environment:
      POSTGRES_PASSWORD: QuVsKppcWvwwX2Vv
    volumes:
      - "/docker/PostgreSQL/data:/var/lib/postgresql/data"
      - "/docker/PostgreSQL/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
  yangxj96-rabbitmq:
    image: rabbitmq:3.11.5
    container_name: yangxj96-rabbitmq
    restart: always
    privileged: true
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: QuVsKppcWvwwX2Vv
    volumes:
      - "/docker/RabbitMQ/config/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "/docker/RabbitMQ/config/:/etc/rabbitmq/conf.d/"
      - "/docker/RabbitMQ/data:/var/lib/rabbitmq"
  yangxj96-redis:
    image: redis:7.0.5-alpine
    container_name: yangxj96-redis
    restart: always
    privileged: true
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "/docker/Redis/data:/data"
      - "/docker/Redis/config/redis.conf:/etc/redis/redis.conf"
  yangxj96-nacos:
    image: yangxj96/nacos-service-pgsql:v2.2.2-2
    container_name: yangxj96-nacos
    restart: always
    privileged: true
    env_file:
      - "/docker/Nacos/env/pgsql.env"
    network_mode: host
    volumes:
      - "/docker/Nacos/logs/:/home/nacos/logs"
    depends_on:
      yangxj96-pgsql:
        condition: service_healthy
  yangxj96-minio:
    image: bitnami/minio:2023.3.24
    container_name: yangxj96-minio
    restart: always
    privileged: true
    network_mode: host
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=QuVsKppcWvwwX2Vv
    volumes:
      - "/docker/Minio/data:/data"
      - "/docker/Minio/config:/root/.minio"
