version: '3'
services:
  support-rabbitmq:
    image: rabbitmq:3.11.5
    container_name: support-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: QPOCe^7Q5qtoPD&O
    volumes:
      - "D:/data/support/rabbitmq/config/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "D:/data/support/rabbitmq/config/:/etc/rabbitmq/conf.d/"
      - "D:/data/support/rabbitmq/data:/var/lib/rabbitmq"
      - "D:/data/support/rabbitmq/log:/var/log/rabbitmq"
    ports:
      - "15691:15691"
      - "15692:15692"
      - "4369:4369"
      - "5671:5671"
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
      - "15670:15670"
      - "15674:15674"
      - "1883:1883"
      - "61613:61613"
    restart: always
    privileged: true
  support-mysql8:
    image: mysql:8.0.31
    container_name: support-mysql8
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "QPOCe^7Q5qtoPD&O"
    volumes:
      - "D:/data/support/mysql8/data:/var/lib/mysql"
    privileged: true
    ports:
      - "13306:3306"
      - "13060:33060"
      - "13062:33062"
  support-redis:
    image: redis:7.0.5-alpine
    container_name: support-redis
    restart: always
    privileged: true
    command: redis-server --port 6379 --requirepass "QPOCe^7Q5qtoPD&O"  --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "D:/data/support/Redis/data:/data"
  support-minio:
    image: bitnami/minio:2023.2.17
    container_name: support-minio
    restart: always
    privileged: true
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=QPOCe^7Q5qtoPD&O
    ports:
      - "9900:9000"
      - "9901:9001"
    volumes:
      - "D:/data/support/MinIO/data:/data"
