version: "3"
services:
  yangxj96-nacos2:
    image: nacos-pgsql:1.0.0
    container_name: yangxj96-nacos2
    privileged: true
    env_file:
      - "/docker/Nacos2/env/pgsql.env"
    network_mode: host
    volumes:
      - "/docker/Nacos2/logs/:/home/nacos/logs"
