version: '3'
services:
  yangxj96-redis:
    image: redis:7.0.5-alpine
    container_name: yangxj96-redis
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - yangxj96
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "/docker/Redis/data:/data"
      - "/docker/Redis/config/redis.conf:/etc/redis/redis.conf"

networks:
  yangxj96:
    external:
      name: yangxj96