---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yangxj96-nacos
spec:
  serviceName: yangxj96-nacos
  replicas: 1
  selector:
    matchLabels:
      app: yangxj96-nacos
  template:
    metadata:
      labels:
        app: yangxj96-nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: yangxj96-nacos
          image: yangxj96/nacos-server-pgsql:v2.2.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
          env:
            - name: MODE
              value: "standalone"
            - name: PREFER_HOST_MODE
              value: hostname
            - name: SPRING_DATASOURCE_PLATFORM
              value: postgresql
            - name: PGSQL_URL
              value: jdbc:postgresql://49.235.101.106:5432/yangxj96_saas_db?currentSchema=db_nacos
            - name: PGSQL_USERNAME
              value: postgres
            - name: PGSQL_PASSWORD
              value: QuVsKppcWvwwX2Vv
      # 这里主要是一个宿主机不部署多个
      # 现在把mode换成了快照,暂时不需要这样处理了
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchExpressions:
      #            - key: "app"
      #              operator: In
      #              values:
      #                - yangxj96-nacos
      #        topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  name: yangxj96-nacos-service
  labels:
    app: yangxj96-nacos-service
spec:
  type: NodePort
  selector:
    app: yangxj96-nacos
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30001
    - port: 9848
      name: client-rpc
      targetPort: 9848
      nodePort: 31001
    - port: 9849
      name: raft-rpc
      targetPort: 9849
      nodePort: 31002
